#!/bin/sh
workspaces() {

ws1="1"
ws2="2"
ws3="3"
ws4="4"
ws5="5"
ws6="6"

wsd=$(hyprctl workspaces -j)
aws=$(hyprctl activeworkspace -j)
awsid=$(echo $aws | jq ".id")

# Unoccupied
un="0"

# check if Occupied
o1=$(echo $wsd | jq ".[] | select(.id == $ws1) | .windows")
o2=$(echo $wsd | jq ".[] | select(.id == $ws2) | .windows")
o3=$(echo $wsd | jq ".[] | select(.id == $ws3) | .windows")
o4=$(echo $wsd | jq ".[] | select(.id == $ws4) | .windows")
o5=$(echo $wsd | jq ".[] | select(.id == $ws5) | .windows")
o6=$(echo $wsd | jq ".[] | select(.id == $ws6) | .windows")

ic_1=""
ic_2=""
ic_3=""
ic_4=""
ic_5=""
ic_6=""
if [ $awsid == 1 ]; then
    ic_1=""
elif [ $awsid == 2 ]; then
    ic_2=""
elif [ $awsid == 3 ]; then
    ic_3=""
elif [ $awsid == 4 ]; then
    ic_4=""
elif [ $awsid == 5 ]; then
    ic_5=""
elif [ $awsid == 6 ]; then
    ic_6=""
fi

echo 	"(box	:class \"works\"	:orientation \"h\" :spacing 5 :space-evenly \"false\" (button :onclick \"hyprctl dispatch workspace $ws1\"	:class	\"$un$o1\"	\"$ic_1\") (button :onclick \"hyprctl dispatch workspace $ws2\"	:class \"$un$o2\"	 \"$ic_2\") (button :onclick \"hyprctl dispatch workspace $ws3\"	:class \"$un$o3\" \"$ic_3\") (button :onclick \"hyprctl dispatch workspace $ws4\"	:class \"$un$o4\"	\"$ic_4\") (button :onclick \"hyprctl dispatch workspace $ws5\"	:class \"$un$o5\" \"$ic_5\")  (button :onclick \"hyprctl dispatch workspace $ws6\"	:class \"$un$o6\" \"$ic_6\"))"

}
workspaces

socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do
  workspaces
    # case line in
    #   workspace*) workspaces ;;
    # esac
done
